<a href="https://colab.research.google.com/github/SuyogPatgave/Python_Codes-Projects/blob/main/CRM_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing library packages

In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Data Import

In [69]:
acc= pd.read_csv('/content/accounts.csv')
data_dic = pd.read_csv('/content/data_dictionary.csv')
prdts = pd.read_csv('/content/products.csv')
sales_pipe = pd.read_csv('/content/sales_pipeline.csv')
sales_team = pd.read_csv('/content/sales_teams.csv')

Consolidating all datasets (assigning names for referential convenience) in one list

In [70]:
datasets = [('accounts', acc), ('data dictionary', data_dic), ('products', prdts), ('sales pipeline', sales_pipe), ('sales team', sales_team)]

Data Visibility

In [71]:
for name, dataset in datasets:
  print(f"\n\n\n{name.title()}:")
  print(dataset.head(10))

Accounts:
            account         sector  year_established  revenue  employees  \
0  Acme Corporation      technolgy              1996  1100.04       2822
1        Betasoloin        medical              1999   251.41        495
2          Betatech        medical              1986   647.18       1185
3        Bioholding        medical              2012   587.34       1356
4           Bioplex        medical              1991   326.82       1016
5          Blackzim         retail              2009   497.11       1588
6     Bluth Company      technolgy              1993  1242.32       3027
7        Bubba Gump       software              2002   987.39       2253
8           Cancity         retail              2001   718.62       2448
9            Cheers  entertainment              1993  4269.90       6472

  office_location     subsidiary_of
0   United States               NaN
1   United States               NaN
2           Kenya               NaN
3      Philipines               NaN
4   United States               NaN
5   United States               NaN
6   United States  Acme Corporation
7   United States               NaN
8   United States               NaN
9   United States   Massive Dynamic



Data Dictionary:
      Table             Field                          Description
0  accounts           account                         Company name
1  accounts            sector                             Industry
2  accounts  year_established                     Year Established
3  accounts           revenue  Annual revenue (in millions of USD)
4  accounts         employees                  Number of employees
5  accounts   office_location                         Headquarters
6  accounts     subsidiary_of                       Parent company
7  products           product                         Product name
8  products            series                       Product series
9  products       sales_price               Suggested retail price



Products:
          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768



Sales Pipeline:
  opportunity_id      sales_agent         product   account deal_stage  \
0       1C1I7A6R      Moses Frase  GTX Plus Basic   Cancity        Won
1       Z063OYW0  Darcel Schlecht          GTXPro     Isdom        Won
2       EC4QE1BX  Darcel Schlecht      MG Special   Cancity        Won
3       MV1LWRNH      Moses Frase       GTX Basic   Codehow        Won
4       PE84CX4O        Zane Levy       GTX Basic    Hatfan        Won
5       ZNBS69V1    Anna Snelling      MG Special  Ron-tech        Won
6       9ME3374G   Vicki Laflamme      MG Special   J-Texon        Won
7       7GN8Q4LL   Markita Hansen       GTX Basic    Cheers        Won
8       OLK9LKZB  Niesha Huffines  GTX Plus Basic  Zumgoity        Won
9       HAXMC4IX   James Ascencio     MG Advanced       NaN   Engaging

  engage_date  close_date  close_value
0  2016-10-20  2017-03-01       1054.0
1  2016-10-25  2017-03-11       4514.0
2  2016-10-25  2017-03-07         50.0
3  2016-10-25  2017-03-09        588.0
4  2016-10-25  2017-03-02        517.0
5  2016-10-29  2017-03-01         49.0
6  2016-10-30  2017-03-02         57.0
7  2016-11-01  2017-03-07        601.0
8  2016-11-01  2017-03-03       1026.0
9  2016-11-03         NaN          NaN



Sales Team:
          sales_agent           manager regional_office
0       Anna Snelling  Dustin Brinkmann         Central
1      Cecily Lampkin  Dustin Brinkmann         Central
2   Versie Hillebrand  Dustin Brinkmann         Central
3     Lajuana Vencill  Dustin Brinkmann         Central
4         Moses Frase  Dustin Brinkmann         Central
5  Jonathan Berthelot     Melvin Marxen         Central
6   Marty Freudenburg     Melvin Marxen         Central
7    Gladys Colclough     Melvin Marxen         Central
8     Niesha Huffines     Melvin Marxen         Central
9     Darcel Schlecht     Melvin Marxen         Central

Data Description

In [72]:
  for name, dataset in datasets:
    print(f"\n\n\n{name.title()}:")
    print(dataset.describe())

Accounts:
       year_established       revenue     employees
count         85.000000     85.000000     85.000000
mean        1996.105882   1994.632941   4660.823529
std            8.865427   2169.491436   5715.601198
min         1979.000000      4.540000      9.000000
25%         1989.000000    497.110000   1179.000000
50%         1996.000000   1223.720000   2769.000000
75%         2002.000000   2741.370000   5595.000000
max         2017.000000  11698.030000  34288.000000



Data Dictionary:
                 Table    Field   Description
count               21       21            21
unique               4       18            19
top     sales_pipeline  account  Company name
freq                 8        2             2



Products:
        sales_price
count      7.000000
mean    6023.571429
std     9388.428070
min       55.000000
25%      823.000000
50%     3393.000000
75%     5151.500000
max    26768.000000



Sales Pipeline:
        close_value
count   6711.000000
mean    1490.915512
std     2320.670773
min        0.000000
25%        0.000000
50%      472.000000
75%     3225.000000
max    30288.000000



Sales Team:
          sales_agent        manager regional_office
count              35             35              35
unique             35              6               3
top     Anna Snelling  Melvin Marxen            East
freq                1              6              12

# Data Pre-Processing

Account Table

In [73]:
acc

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,NaN
1,Betasoloin,medical,1999,251.41,495,United States,NaN
2,Betatech,medical,1986,647.18,1185,Kenya,NaN
3,Bioholding,medical,2012,587.34,1356,Philipines,NaN
4,Bioplex,medical,1991,326.82,1016,United States,NaN
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,NaN
81,Zencorporation,technolgy,2011,40.79,142,China,NaN
82,Zoomit,entertainment,1992,324.19,978,United States,NaN
83,Zotware,software,1979,4478.47,13809,United States,NaN
84,Zumgoity,medical,1984,441.08,1210,United States,NaN

In [74]:
acc_cols = acc[['account', 'sector', 'office_location', 'subsidiary_of']]

In [75]:
for columns in acc_cols:
  print(f"\n\n\nColumn Name: {acc_cols[columns].name}")
  print(f"Number of Null values: {acc_cols[columns].isnull().sum()}")
  print(acc_cols[columns].value_counts())

Column Name: account
Number of Null values: 0
account
Acme Corporation    1
Betasoloin          1
Betatech            1
Bioholding          1
Bioplex             1
                   ..
Zathunicon          1
Zencorporation      1
Zoomit              1
Zotware             1
Zumgoity            1
Name: count, Length: 85, dtype: int64



Column Name: sector
Number of Null values: 0
sector
retail                17
technolgy             12
medical               12
marketing              8
finance                8
software               7
entertainment          6
telecommunications     6
services               5
employment             4
Name: count, dtype: int64



Column Name: office_location
Number of Null values: 0
office_location
United States    71
Kenya             1
Philipines        1
Japan             1
Italy             1
Norway            1
Korea             1
Jordan            1
Brazil            1
Germany           1
Panama            1
Belgium           1
Romania           1
Poland            1
China             1
Name: count, dtype: int64



Column Name: subsidiary_of
Number of Null values: 70
subsidiary_of
Acme Corporation    4
Sonron              3
Bubba Gump          2
Golddex             2
Inity               2
Massive Dynamic     1
Warephase           1
Name: count, dtype: int64

In [76]:
acc.subsidiary_of =  acc.subsidiary_of.fillna('Not a Subsidiary')
acc

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,Not a Subsidiary
1,Betasoloin,medical,1999,251.41,495,United States,Not a Subsidiary
2,Betatech,medical,1986,647.18,1185,Kenya,Not a Subsidiary
3,Bioholding,medical,2012,587.34,1356,Philipines,Not a Subsidiary
4,Bioplex,medical,1991,326.82,1016,United States,Not a Subsidiary
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,Not a Subsidiary
81,Zencorporation,technolgy,2011,40.79,142,China,Not a Subsidiary
82,Zoomit,entertainment,1992,324.19,978,United States,Not a Subsidiary
83,Zotware,software,1979,4478.47,13809,United States,Not a Subsidiary
84,Zumgoity,medical,1984,441.08,1210,United States,Not a Subsidiary

Products Table

In [77]:
prdts

          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768

Sales Pipeline

In [78]:
sales_pipe

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0
...,...,...,...,...,...,...,...,...
8795,9MIWFW5J,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,NaN
8796,6SLKZ8FI,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,NaN
8797,LIB4KUZJ,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,NaN
8798,18IUIUK0,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,NaN
8799,8I5ONXJX,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,NaN

In [84]:
sales_pipe_cols = sales_pipe[['sales_agent', 'product', 'account', 'deal_stage']]

In [86]:
for values in sales_pipe_cols:
  print(f"\n\n\n{values}")
  print(f"Number of Null values: {sales_pipe_cols[values].isnull().sum()}")
  print(sales_pipe_cols[values].value_counts())

sales_agent
Number of Null values: 0
sales_agent
Darcel Schlecht       747
Vicki Laflamme        451
Anna Snelling         448
Kary Hendrixson       438
Kami Bicknell         362
Versie Hillebrand     361
Zane Levy             349
Cassey Cress          346
Jonathan Berthelot    345
Gladys Colclough      317
Lajuana Vencill       311
Corliss Cosme         310
Markita Hansen        306
Maureen Marcano       285
Marty Freudenburg     281
Donn Cantrell         275
James Ascencio        267
Violet Mclelland      261
Moses Frase           260
Daniell Hammack       259
Niesha Huffines       239
Reed Clapper          237
Boris Faz             210
Cecily Lampkin        203
Hayden Neloms         202
Elease Gluck          177
Rosalina Dieter       160
Rosie Papadopoulos    160
Garret Kinder         123
Wilburn Farren        110
Name: count, dtype: int64



product
Number of Null values: 0
product
GTX Basic         1866
MG Special        1651
GTXPro            1480
MG Advanced       1412
GTX Plus Basic    1383
GTX Plus Pro       968
GTK 500             40
Name: count, dtype: int64



account
Number of Null values: 1425
account
Hottechi                 200
Kan-code                 196
Konex                    178
Condax                   170
Dontechi                 129
                        ...
Newex                     55
Bioplex                   53
The New York Inquirer     52
Sumace                    52
Iselectrics               51
Name: count, Length: 85, dtype: int64



deal_stage
Number of Null values: 0
deal_stage
Won            4238
Lost           2473
Engaging       1589
Prospecting     500
Name: count, dtype: int64